SET IDENTITY_INSERT INSTITUTION OFF
INSERT INTO INSTITUTION (ID, [NAME], PHONE, EMAIL) VALUES (1, 'CET', 1112345678, 'cet@cet.com.br');
INSERT INTO INSTITUTION (ID, [NAME], PHONE, EMAIL) VALUES (2, 'ELETROPAULO', 1112345678, 'eletropaulo@eletropaulo.com.br');
INSERT INTO INSTITUTION (ID, [NAME], PHONE, EMAIL) VALUES (3, 'SABESP', 1112345678, 'sabesp@sabesp.com.br');
SET IDENTITY_INSERT INSTITUTION ON

SET IDENTITY_INSERT OCCURRENCE_TYPE OFF
INSERT INTO OCCURRENCE_TYPE (ID, [NAME]) VALUES (1, 'Trânsito');
INSERT INTO OCCURRENCE_TYPE (ID, [NAME]) VALUES (2, 'Energia');
INSERT INTO OCCURRENCE_TYPE (ID, [NAME]) VALUES (3, 'Saneamento');
SET IDENTITY_INSERT OCCURRENCE_TYPE ON

SET IDENTITY_INSERT OCCURRENCE_SUBTYPE OFF
INSERT INTO OCCURRENCE_SUBTYPE (ID, OCCURRENCE_TYPE_ID, [NAME]) VALUES (1, 'Obstrução de Via', 1);
INSERT INTO OCCURRENCE_SUBTYPE (ID, OCCURRENCE_TYPE_ID, [NAME]) VALUES (2, 'Veículo em Local Irregular', 1);
INSERT INTO OCCURRENCE_SUBTYPE (ID, OCCURRENCE_TYPE_ID, [NAME]) VALUES (3, 'Manutenção de Radar', 1);
INSERT INTO OCCURRENCE_SUBTYPE (ID, OCCURRENCE_TYPE_ID, [NAME]) VALUES (4, 'Manutenção da Rede Elétrica', 2);
INSERT INTO OCCURRENCE_SUBTYPE (ID, OCCURRENCE_TYPE_ID, [NAME]) VALUES (5, 'Remoção de Ilegalidades', 2);
INSERT INTO OCCURRENCE_SUBTYPE (ID, OCCURRENCE_TYPE_ID, [NAME]) VALUES (6, 'Instalação de Poste', 2);
INSERT INTO OCCURRENCE_SUBTYPE (ID, OCCURRENCE_TYPE_ID, [NAME]) VALUES (7, 'Manutenção de Rede de Esgoto', 3);
INSERT INTO OCCURRENCE_SUBTYPE (ID, OCCURRENCE_TYPE_ID, [NAME]) VALUES (8, 'Falta de Água', 3);
INSERT INTO OCCURRENCE_SUBTYPE (ID, OCCURRENCE_TYPE_ID, [NAME]) VALUES (9, 'Instalação de Rede de Esgoto', 3);
SET IDENTITY_INSERT OCCURRENCE_SUBTYPE ON

SET IDENTITY_INSERT [USER] OFF
INSERT INTO [USER] (ID, [USERNAME], EMAIL, [PASSWORD], INSTITUTION_ID) VALUES (1, 'CET', 'cet@cet.com.br', '12345678', 1);
INSERT INTO [USER] (ID, [USERNAME], EMAIL, [PASSWORD], INSTITUTION_ID) VALUES (2, 'ELETROPAULO', 'eletropaulo@eletropaulo.com.br', '12345678', 2);
INSERT INTO [USER] (ID, [USERNAME], EMAIL, [PASSWORD], INSTITUTION_ID) VALUES (3, 'SABESP', 'sabesp@sabesp.com.br', '12345678', 3);
SET IDENTITY_INSERT [USER] ON