GDFtemp = {
    langen: "English",
    langpt: "Português",
    orientationPortrait: "Retrato",
    orientationLandscape: "Paisagem",
    orientationAutomatic: "Destravada",
    orientation: "Orientação",

    loadingMessage: "<h1>Carregando...</h1>",
    loginPasswordError: "Usuário ou senha incorretos.",
    loginErrorUserPassword: "Por favor, forneça o Usuário e a Senha.",
    generalRequestError: "Erro ao concluir a solicitação.",
    error: "Erro",
    errorMessageTimeout: "Tempo limite de conexão atingido.",
    errorMessageParserError: "Erro na interpretação do conteúdo (parser error).",
    errorMessageConnection: "Houve um erro de rede/internet durante a requisição.",
    errorMessageUnauthorized: "Não autorizado.",
    errorMessageForbidden: "Acesso negado.",
    errorMessageNotFound: "O endereço requisitado não foi encontrado.",
    errorMessageServer: "Houve um erro interno do servidor.",
    errorInvalidDecimal: "Decimal inválido.",
    errorMinValue: "Número digitado menor que o mínimo",
    errorMaxValue: "Número digitado maior que o máximo",
    erroNoValue: "Valor não informado!",

    privateDeviceId: "O ID informado é reservado para uso interno.",

    confirmClose: "Deseja realmente encerrar o aplicativo?",
    cancel: "Cancelar",
    yes: "Sim",
    no: "Não",
    ok: "OK",
    message: "Mensagem",
    close: "Fechar",
    save: "Salvar",
    none: "Nenhum",
    noneF: "Nenhuma",
    unknown: "Desconhecido",
    unspecified: "Não especificado",
    username: "Nome de usuário",
    selectAnOption: "Selecione...",
    deleteLabel: "Excluir",
    searchPlaceHolder: "Pesquisar...",
    pullToRefresh: "Puxe para atualizar",
    refreshing: "Atualizando",
    releaseToRefresh: "Solte para atualizar",
    version: "Versão: {0}",
    password: "Senha",
    enter: "Entrar",

    logout: "Sair",
    login: "Login",
    settings: "Configurações",
    user: "Usuário",
    about: "Sobre",
    sync: "Sincronia",
    themecolor: "Cor do Sistema",

    lookUpTitle: "Lista de {0}",
    lookUpNoDataDefaultMessage: "Nenhum registro encontrado.",

    languageChangeInfo: "O app deve ser reiniciado para que essa configuração tenha efeito.",
    map: "Mapa",
    appGeneralSettings: "Geral",
    appGeneralSettingsRestartNeeded: "Geral (reinício necessário)",
    language: "Idioma",
    languageAutomatic: "Automático",
    saveLog: "Gravar logs",
    showLog: "Mostrar log",
    logviewer: "Log",
    logFileExportedSuccessfully: "Arquivo de log exportado com sucesso na pasta Log.",
    logFileNotExportedSuccessfully: "Erro ao exportar arquivo de log.",
    deleteLog: "Deseja deletar o log da aplicação?",
    D4Info: "{0} no banco de dados: {1}",
    records: "Registros",
    forceTabletLayout: "Forçar layout de tablet",
    restartNeededInfo: "O app deve ser reiniciado para que essa configuração tenha efeito.",
    deviceInformation: "Informação do Device",
    deviceId: "ID do device",
    deviceModel: "Modelo",
    deviceOperatingSystem: "Sistema operacional",
    webServiceConfiguration: "Configuração da WebAPI",
    serviceUrl: "URL",
    serviceUser: "Usuário",
    servicePassword: "Senha",
    clearDatabase: "Limpar base de dados",
    clearDatabaseConfirmation: "Tem certeza de que deseja limpar a base de dados? As informações excluídas não poderão ser recuperadas.",

    lastSyncInformation: "Informações da última sincronia",
    lastDate: "Última data",
    syncFilters: "Filtros para carga de dados",
    syncLoadFilters: "Carregar filtros",
    synchronize: "Sincronizar",
    upload: "Enviar",
    syncConnectionError: "Uma conexão de rede é necessária para a execução da sincronia",
    syncConfigError: "As configurações do Web Service não estão completas",
    syncEmptyFields: "'Safra' e 'Fazenda' são campos obrigatórios.",
    syncCompanyEmpty: "Você deve informar uma Empresa.",
    syncDatabaseError: "Houve um erro ao atualizar a base de dados.",
    syncWarning: "Você deve realizar um sincronismo completo. Restam {0} dias antes do aplicativo ser bloqueado.",
    syncRequired: "Você deve realizar um sincronismo completo para continuar.",

    formErrorEmptyFields: "Por favor, preencha todos os campos.",
    formNumericFieldError: "O campo '{0}' deve ser numérico.",

    deleteItem: "Deseja remover esse {0}?",

    selectBefore: "Selecione {0} primeiro.",
    removeItem: "Deseja remover este item?",

    mapAlreadyUpdated: "Mapa já atualizado.",
    mapFileNotFound: "Arquivo de mapa não encontrado no dispositivo.",
    mapUpdateError: "Ocorreu algum erro para atualizar o mapa.",
    mapUpdateSuccess: "Mapa atualizado com sucesso.",
    noMapsInDatabase: "Não há mapa no banco de dados. Por favor, atualize o mapa.",
    noSignalGps: "Sinal de GPS fraco ou indisponível. Tente novamente.",
    gpsError: "Erro de GPS: {0}. Deseja tentar novamente?",
    divi4NotFound: "{0} não encontrado",
    gpsVectorNotFound: "A Coordenada recuperada não foi localizada na base de dados. Deseja tentar novamente?",

    updateMap: "Atualizar Mapa",
    updatingMap: "Atualizando Mapa",
    constantMapError: "Configuração da constante 'hasMapDb' não realizada!",
    thereIsEntryToSend: "Há lançamentos pendentes. Realize uma sincronia com um usuário normal.",
    notFound: "Não encontrado",
    allEntryDeleted: "Todos lançamentos deletados.",

    company: "Empresa",
    crop: "Safra",
    syncSuccess: "Sincronia realizada com sucesso!",
    uploadSuccess: "Envio realizado com sucesso",
    syncBlockSuccess: "Sincronizado realizada com sucesso, você será redirecionado para a tela de login!",
    backNewEntry: "O lançamento foi iniciado. Deseja realmente abandoná-lo?",

    syncPendent: "O processo de sincronismo foi interrompido! Realize um novo sincronismo para continuar!",

    recoveringCoord: "Recuperando coordenadas pelo GPS...",
    requestWebService: "Requisitando Web Service...",
    loadingFilters: "Carregando filtros...",
    startSync: "Iniciando a sincronia dos dados...",
    preparingDataToSend: "Preparando dados para envio...",
    syncing: "Atualizando informações...",
    cleaningDatabase: "Limpando dados enviados...",
    insertingDatabase: "Inserindo novos dados...",
    finishSync: "Finalizando sincronia. Por favor aguarde...",
    finishUpload: "Finalizando envio de dados. Por favor aguarde...",
    startUpdateMap: "Iniciando a atualização do mapa...",
    startingAutomaticD4: "Iniciando o reconhecimento automático do talhão...",
    exportingLog: "Exportando log...",

    colorpreviewtext: "Texto de exemplo",
    fixedThemes: "Themas fixos",

    deviceKey: "Device Key",
    warning: "Aviso:",
    passwordWarning: "ID exclusivo para uso de desenvolvedores favor digitar senha",

    passwordLabel: "Senha:",
    delLookUp: "Confirma exclusão de {0}?",
    delLookUpNotAllowed: "Exclusão não permitida.<br /> {0} é obrigatório para informar {1}.",
    
    insertItem: "Inserir {0}",
    itemAlreadyExists: "Este item já existe na lista",
    itemInvalid: "Item invalido.",
    itemAdded: "Item inserido com sucesso",
    itemDeleted: "Item excluido com sucesso",

    welcome: "Bem-vindo",
    welcomeText: "A GAtec agradece pela aquisição do modulo {0}. Siga os passos exibidos para configurar seu aplicativo e deixa-lo pronto para uso ",
    setDescText: "Defina uma descrição para este dispositivo ",
    deviceDesc: "Aguarde enquanto o dispositivo é registrado",
    setURIText: "Insira o endereço de sincronia",
    registerDevice: "Registrar",
    newDeviceInfoText: "Seu ID é: {0}. \n Você pode consultar seu ID mais tarde acessando a opção \"Sobre\" no menu principal ",
    remainingChars: "Caracteres restantes: {0}",

    cleanAgps: "Utilizar limpeza de cache AGPS",

    erroDuasUrlsFalsas: "As duas URLs estão incorretas",
    serviceUrlIntern: "URL Interna",
    selectAllLabel: "Marcar todos",
    unselectAllLabel: "Desmarcar todos",

    validatingData: "Validando dados...",
    savingData: "Salvanda dados",

    commitEditChangesError: "Erro ao confirmar edição. Por favor, contate o suporte",
    getEntryInfoError: "Erro ao obter informações. Por favor, contate o suporte",
    insertByObjError: "Erro ao inserir informação. Por favor, contate o suporte",
    takeLastItemError: "Erro ao obter ultima informação inserida. Por favor, contate o suporte."
};