GDFtemp = {
    langen: "English",
    langpt: "Português",
    orientationPortrait: "Portrait",
    orientationLandscape: "Landscape",
    orientationAutomatic: "Unlocked",
    orientation: "Orientation",

    loadingMessage: "<h1>Loading...</h1>",
    loginPasswordError: "Wrong username or password.",
    loginErrorUserPassword: "You must provide User and Password.",
    generalRequestError: "Request completed with errors.",
    error: "Error",
    errorMessageTimeout: "Connection timed out.",
    errorMessageParserError: "Content parse error.",
    errorMessageConnection: "A network/internet error occurred.",
    errorMessageUnauthorized: "Unauthorized.",
    errorMessageForbidden: "Access denied.",
    errorMessageNotFound: "The requested URL was not found.",
    errorMessageServer: "An internal server error occurred.",
    errorInvalidDecimal: "Invalid decimal.",
    errorMinValue: "Number typed less than minimum",
    errorMaxValue: "Number typed more than maximum",
    erroNoValue: "No set value!",

    privateDeviceId: "The informed device id, is private for internal use.",

    confirmClose: "Do you really want to close the application?",
    cancel: "Cancel",
    yes: "Yes",
    no: "No",
    ok: "OK",
    message: "Message",
    close: "Close",
    save: "Save",
    none: "None",
    noneF: "None",
    unknown: "Unknown",
    unspecified: "Unspecified",
    username: "Username",
    selectAnOption: "Select...",
    deleteLabel: "Delete",
    searchPlaceHolder: "Search...",
    pullToRefresh: "Pull to refresh",
    refreshing: "Refreshing",
    releaseToRefresh: "Release to refresh",
    version: "Version: {0}",
    password: "Password",
    enter: "Enter",

    logout: "Logout",
    login: "Login",
    settings: "Settings",
    user: "User",
    about: "About",
    sync: "Synchronization",
    themecolor: "Themecolor",

    lookUpTitle: "{0} List",
    lookUpNoDataDefaultMessage: "No data found.",

    languageChangeInfo: "The app must be restarted for this setting to take effect.",
    map: "Map",
    appGeneralSettings: "General",
    appGeneralSettingsRestartNeeded: "General (app restart needed)",
    language: "Language",
    languageAutomatic: "Automatic",
    saveLog: "Save logs",
    showLog: "Show log",
    logviewer: "Log",
    logFileExportedSuccessfully: "Log file exported successfully on LOG folder.",
    logFileNotExportedSuccessfully: "Error to export log file.",
    deleteLog: "Do you really want to delete the application log?",
    D4Info: "{0} in database: {1}",
    records: "Records",
    forceTabletLayout: "Force tablet layout",
    restartNeededInfo: "The app must be restarted for this setting to take effect.",
    deviceInformation: "Device Information",
    deviceId: "Device ID",
    deviceModel: "Model",
    deviceOperatingSystem: "Operating system",
    webServiceConfiguration: "WebAPI Configuration",
    serviceUrl: "URL",
    serviceUser: "User",
    servicePassword: "Password",
    clearDatabase: "Clear database",
    clearDatabaseConfirmation: "Are you sure you want to clear the database? The deleted data will not be recoverable.",

    lastSyncInformation: "Last Synchronization Information",
    lastDate: "Last date",
    syncFilters: "Data load filters",
    syncLoadFilters: "Load filters",
    synchronize: "Synchronize",
    upload: "Upload",
    syncConnectionError: "A network connection is necessary to execute the synchronization",
    syncConfigError: "The Web Service configuration is not complete",
    syncEmptyFields: "'Crop' and 'Company' are mandatory fields.",
    syncCompanyEmpty: "You must provide a Company.",
    syncDatabaseError: "There was an error updating the database.",
    syncWarning: "You must execute a full sync. {0} days left before the app is blocked.",
    syncRequired: "You must execute a full sync to continue.",

    formErrorEmptyFields: "Please fill all the fields.",
    formNumericFieldError: "The field '{0}' must be numeric.",

    deleteItem: "Do you want to remove this {0}?",

    selectBefore: "Select {0} before.",
    removeItem: "Do you want to remove this item?",

    mapAlreadyUpdated: "Map already updated.",
    mapFileNotFound: "Map file not found on device.",
    mapUpdateError: "Occurred some error to update map.",
    mapUpdateSuccess: "Map updated successfully.",
    noMapsInDatabase: "There isn't map on database.",
    noSignalGps: "No GPS signal. Active and try again.",
    gpsError: "GPS Error: {0}. Do you want to try again?",
    divi4NotFound: "{0} not found",
    gpsVectorNotFound: "The coordinate recovered was not found in the database. Do you want to try again?",

    updateMap: "Update Map",
    updatingMap: "Updating Map",
    constantMapError: "hasMapDb not informed on constants!",
    thereIsEntryToSend: "There are pending entries. Perform a sync with a normal user.",
    notFound: "Not Found",
    allEntryDeleted: "All entries deleted.",

    company: "Company",
    crop: "Crop",
    syncSuccess: "Synchronized successfully!",
    uploadSuccess: "Uploaded successfully",
    syncBlockSuccess: "Synchronized successfully, you'll redirect to login!",
    backNewEntry: "The Entry was started. Do you really want to leave it?",

    syncPendent: "The sync proccess has been stoped. Perform a new sync to continue",

    recoveringCoord: "Recovering coordinated by GPS",
    requestWebService: "Requesting Web Service...",
    loadingFilters: "Loading filters...",
    startSync: "Starting the data sync...",
    preparingDataToSend: "Preparing data to send...",
    syncing: "Syncing data...",
    cleaningDatabase: "Cleaning sent data...",
    insertingDatabase: "Inserting new database...",
    finishSync: "Finishing sync. Please wait...",
    finishUpload: "Finishing upload. Please wait...",
    startUpdateMap: "Starting map update...",
    startingAutomaticD4: "Starting Automatic D4",
    exportingLog: "Exporting log...",

    colorpreviewtext: "Sample Text",
    fixedThemes: "Fixed themes",

    deviceKey: "Device Key",

    warning: "Warning:",
    passwordWarning: "This ID is exclusive only to developer",

    passwordLabel: "Password:",
    delLookUp: "Confirm delete of {0}?",
    delLookUpNotAllowed: "Delete not allowed.<br /> {0} is required to {1}.",

    insertItem: "Insert {0}",
    itemAlreadyExists: "This item already exists",
    itemInvalid: "This item is invalid",
    itemAdded: "Item added",
    itemDeleted: "Item deleted",

    welcome: "Welcome",
    welcomeText: "The GAtec thank its acquisition of {0} app. Follow next steps to configure your app",
    setDescText: "Inform a description to this device",
    deviceDesc: "Hold on while the app is been registered",
    setURIText: "Inform the syncronize URL",
    registerDevice: "Register",
    newDeviceInfoText: "Your ID is: {0}. \n You can consult your id latter using \"About\" option",
    remainingChars: "Characters remaining: {0}",

    cleanAgps: "Enable cache AGPS clean",

    erroDuasUrlsFalsas: "Both URL are incorrect",
    serviceUrlIntern: "Intern URL",
    selectAllLabel: "Select All",
    unselectAllLabel: "Unselect All",

    validatingData: "Validating data...",
    savingData: "Saving data...",

    commitEditChangesError: "Error while commiting data changes. Please contact support.",
    getEntryInfoError: "Error fetching data. Please contact support.",
    insertByObjError: "Error inserting data. Please contact support.",
    takeLastItemError: "Error fetching last data. Please contact support."
};